### PR TITLE
Added ":" infront of LLMatic in the name of the paper

### PR DESCRIPTION
**Pull request by umair-nasir14**
Apologies for such a naive mistake to forget that! 

Also, the badge for NAS is not showing, probably because I did not add it correctly?

### CODE REVIEW

**Comment by Aneoshun** [comment]
Thanks for fixing this. 

Btw, you can use add_paper.py python script to populate the list of papers automatically from the data in Arxiv. 

For the NAS tag, you have to add it there as well: 
https://github.com/quality-diversity/quality-diversity.github.io/blob/e0c1a9ac72bddf8efd8b752b8b534433ea7d73a2/papers.md?plain=1#L27
and here to pick a colour:
https://github.com/quality-diversity/quality-diversity.github.io/blob/e0c1a9ac72bddf8efd8b752b8b534433ea7d73a2/assets/css/style.scss#L21

**Comment by umair-nasir14** [comment]
Sure, I will add the tag now.

> Btw, you can use add_paper.py python script to populate the list of papers automatically from the data in Arxiv.

Actually, it had the following error which I wanted to fix in a couple of days:

> Traceback (most recent call last):
>  File "C:\Users\DELL\Projects\Research\quality-diversity.github.io\add_paper.py", line 110, in <module>
>   contents = f.readlines()
>File "C:\Users\DELL\anaconda3\envs\nas\lib\encodings\cp1252.py", line 23, in decode
>    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
>UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 5420: character maps to <undefined>

I wanted to see why it is having issues adding content to the yml files

**Comment by umair-nasir14** [comment]
Changed as you directed. Added red colour to stay in RGB spectrum ;).

**Comment by umair-nasir14** [comment]
Changed as you directed. Added red colour to stay in RGB spectrum ;).

**Pull request merged**
